mode = "backtest_trading" # "backtest_trading" - "paper_trading" - "real_trading"
data_format = "csv" # "csv" - "sql" - "nosql"
db_file = "sqlite:///data/data.db"
csv_dir = "data/"
mongo_port = ""
exchanges = [
    {
        "id":0,
        "name":"binance",
        "fees":{
            "maker":0.001,
            "taker":0.001
        }
    },
    {
        "id":1,
        "name":"bittrex",
        "fees":{
            "maker":0.0025,
            "taker":0.0025
        }
    },
    {
        "id":2,
        "name":"bitfinex",
        "fees":{
            "maker":0.001,
            "taker":0.002
        }
    },
    {
        "id":3,
        "name":"bitstamp",
        "fees":{
            "maker":0.0025,
            "taker":0.0025
        }
    },
    {
        "id":4,
        "name":"cex",
        "fees": {
            "maker":0.0016,
            "taker":0.0025
        }
    },
    {
        "id":5,
        "name":"coinex",
        "fees":{
            "maker":0,
            "taker":0.001
        },
    },
    {
        "id":6,
        "name":"exmo",
        "fees":{
            "maker":0.002,
            "taker":0.002
        }
    },
    {
        "id":7,
        "name":"gatecoin",
        "fees":{
            "maker":0.0025,
            "taker":0.0035
        }
    },
    {
        "id":8,
        "name":"gateio",
        "fees":{
            "maker":0.002,
            "taker":0.002
        }
    },
    {
        "id":9,
        "name":"gdax",
        "fees":{
            "maker":0.00,
            "taker":0.0025
        }
    },
    {
        "id":10,
        "name":"gemini",
        "fees":{
            "maker":0.0025,
            "taker":0.0025
        }
    },
    {
        "id":11,
        "name":"hitbtc",
        "fees":{
            "maker":-0.0001,
            "taker":0.001
        }
    },
    {
        "id":12,
        "name":"huobipro",
        "fees":{
            "maker":0.002,
            "taker":0.002
        }
    },
    {
        "id":13,
        "name":"kraken",
        "fees":{
            "maker":0.0016,
            "taker":0.0026
        }
    },
    {
        "id":14,
        "name":"kukoin",
        "fees": {
            "maker":0.001,
            "taker":0.001
        }
    },
    {
        "id":15,
        "name":"okex",
        "fees":{
            "maker":0.002,
            "taker":0.002
        }
    },
    {
        "id":16,
        "name":"poloniex",
        "fees":{
            "maker":0.0015,
            "taker":0.0025
            }
    },
    {
        "id":17,
        "name":"yobit",
        "fees":{"maker":0.002, "taker":0.002}
    }
]
data_type = [
    {
        "id":0,
        "name":"orderbook"
    },
    {
        "id":1,
        "name":"candles"
    },
    {
        "id":2,
        "name":"tickers"
    },
]
strategies = {
    "virtual_transfers":[
        {
            "ticker":"BTC/USD",
            "exchange_ids":[0,1,2,3],
            "data_type_id":[0]
        },
        {
            "ticker":"ETH/BTC",
            "exchange_ids":[0,1,2],
            "data_type_id":[0]
        },
        {
            "ticker":"DASH/BTC",
            "exchange_ids":[2,3],
            "data_type_id":[0,1]
        }
    ],
    "volume":[
        {
            "ticker":"BTC/USD",
            "exchange_ids":[0],
            "data_type_id":[0, 1]
        }
    ]
}